### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by raspi** [EveAeternam/pi-router-admin#1]
Quickly looked at the code and it's full of security holes (SQL injection, XSS, CSRF, ..). 

You really should read and implement

* https://secure.php.net/manual/en/security.php
* http://www.phptherightway.com/
* https://paragonie.com/blog/2017/12/2018-guide-building-secure-php-software

**Comment by EveAeternam** [comment]
Yes, right now any PHP or SQL is for debugging purposes. This is really just a "theme" for the time being. But thanks for the heads up!
